# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 16 Feb 2022 03:41:35 +0000
*               @ALL          1
*               @user         8
