<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Wed, 16 Feb 2022 03:41:35 +0000
 */
$conf['title'] = 'teste-primeiro';
$conf['lang'] = 'pt-br';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
