# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 16 Feb 2022 03:41:35 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$fH2gJLI2d56B7NNEsDvqYOsndCLqeGxLidVpkudJxQhUPWyYITjjW:admin:admin@admin.com.br:admin,user
